# Generated by Django 4.2.2 on 2023-07-11 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_slug', models.SlugField(blank=True, verbose_name='الإسم التعريفي')),
                ('Pro_FirstName', models.CharField(db_index=True, max_length=50, verbose_name='الإسم الأول')),
                ('Pro_FatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الاب')),
                ('Pro_GrandFatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الجد')),
                ('Pro_FamilyName', models.CharField(db_index=True, max_length=50, verbose_name='إسم العائلة')),
                ('Pro_Mobile', models.CharField(blank=True, db_index=True, default='+966555555555', max_length=10, null=True, verbose_name='الجوال')),
                ('Pro_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
