# Generated by Django 4.2.2 on 2023-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='Pro_Mobile',
            field=models.CharField(blank=True, db_index=True, default='+966555555555', max_length=13, null=True, verbose_name='الجوال'),
        ),
    ]
