# Generated by Django 4.2.2 on 2023-07-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_profilemodel_pro_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Pro_slug',
        ),
    ]
