# Generated by Django 4.2.2 on 2023-07-17 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0003_remove_profilemodel_pro_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileMODEL',
            new_name='Profile_MODEL',
        ),
    ]
