# Generated by Django 4.2.2 on 2023-07-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_rename_pro_mobile_profile_model_pro_mobilennumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_model',
            name='Pro_FamilyName',
        ),
        migrations.RemoveField(
            model_name='profile_model',
            name='Pro_FirstName',
        ),
    ]
