# Generated by Django 4.2.2 on 2023-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_remove_profile_model_pro_familyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_model',
            old_name='Pro_User',
            new_name='user',
        ),
    ]
