# Generated by Django 4.2.2 on 2023-07-19 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0008_rename_user_profile_model_pro_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_MODEL',
            new_name='UserProfile_MODEL',
        ),
    ]
