# Generated by Django 4.2.4 on 2023-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail_model',
            name='date_added_now',
        ),
    ]
