# Generated by Django 4.2.4 on 2023-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.PositiveIntegerField(blank=True, default=15, null=True, verbose_name='Tax %')),
                ('divide_one_hundred', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='100')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxs',
                'ordering': ('-tax_rate',),
            },
        ),
    ]
