# Generated by Django 4.2.4 on 2023-09-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_model',
            name='total_service_charges',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='0'),
        ),
    ]
