# Generated by Django 4.2.4 on 2023-09-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_tax_model_total_service_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_model',
            name='divide_one_hundred',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True, verbose_name='100'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=10, null=True, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='total_service_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='0'),
        ),
    ]
