# Generated by Django 4.2.4 on 2023-09-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax_model',
            name='total_service_charges',
        ),
        migrations.AddField(
            model_name='tax_model',
            name='service_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Service Charges'),
        ),
    ]
