# Generated by Django 4.2.4 on 2023-09-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax', '0007_alter_tax_model_tax_accountant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax_model',
            name='tax_accountant',
        ),
        migrations.AddField(
            model_name='tax_model',
            name='tax_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tax_relation', to=settings.AUTH_USER_MODEL, verbose_name='Tax Accountant'),
        ),
    ]
