# Generated by Django 4.2.4 on 2023-09-30 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_orderdetail', '0001_initial'),
        ('tax', '0008_remove_tax_model_tax_accountant_tax_model_tax_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_model',
            name='tax_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tax_relation', to='order_orderdetail.ordermodel', verbose_name='Order Tax'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tax_relation', to=settings.AUTH_USER_MODEL, verbose_name='User Tax'),
        ),
    ]
