# Generated by Django 4.2.4 on 2023-10-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cate_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('Cate_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('Cate_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Catgory_File_Photo/', verbose_name='Image Preview')),
                ('Cate_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('Cate_name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategoryMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCat_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('SubCat_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('SubCat_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Sub_Catgories_File_Photo/', verbose_name='Image Preview')),
                ('SubCat_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('SubCat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_sub', to='category.categorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ('SubCat_name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategoryBranchMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCatBra_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('SubCatBra_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('SubCatBra_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Sub_Catgories_Branch_File_Photo/', verbose_name='Image Preview')),
                ('SubCatBra_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('SubCatBra_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_branch', to='category.subcategorymodel', verbose_name='Sub Category Branch')),
            ],
            options={
                'verbose_name': 'Sub Category Branch',
                'verbose_name_plural': 'Sub Categories Branch',
                'ordering': ('SubCatBra_name',),
            },
        ),
    ]
