# Generated by Django 4.2.4 on 2023-10-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productmodel_product_category'),
        ('category', '0002_remove_subcategorybranchmodel_subcatbra_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoryBranchMODEL',
        ),
    ]
