# Generated by Django 4.2.4 on 2023-10-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.subcategorybranchmodel', verbose_name='Sub Category Branch'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductImageMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Productes_File_Photo/', verbose_name='Image Preview')),
                ('ProductImage_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages_product', to='product.productmodel', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Products Images',
                'ordering': ('-ProductImage_product',),
                'index_together': {('id',)},
            },
        ),
    ]
