# Generated by Django 4.2.4 on 2023-10-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_subcategorybranchmodel_subcatbra_category'),
        ('product', '0007_alter_productmodel_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_subcategorybranch', to='category.subcategorymodel', verbose_name='Sub Category Branch'),
        ),
    ]
