# Generated by Django 4.2.4 on 2023-09-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentTrackMODEL',
        ),
    ]
