# Generated by Django 4.2.4 on 2023-09-08 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_orderdetail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track_shipment', '0002_delete_shipmenttrackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTrackMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_track_confirmed_order', models.BooleanField(default=False)),
                ('shipment_track_Processing_order', models.BooleanField(default=False)),
                ('shipment_track_dispatch_product', models.BooleanField(default=False)),
                ('shipment_track_delivery', models.BooleanField(default=False)),
                ('shipment_track_Product_delivered', models.BooleanField(default=False)),
                ('shipment_track_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_orderdetail.ordermodel')),
                ('shipment_track_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment Track',
                'verbose_name_plural': 'Shipment Tracs',
                'ordering': ('-shipment_track_order_id',),
            },
        ),
    ]
