# Generated by Django 4.2.4 on 2023-09-10 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_orderdetail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track_shipment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_order_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_orderdetail.ordermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
