# Generated by Django 4.2.4 on 2023-09-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_orderdetail', '0001_initial'),
        ('track_shipment', '0004_alter_shipmenttrackmodel_shipment_track_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_order_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_orderdetail.ordermodel'),
        ),
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
