# Generated by Django 4.2.4 on 2023-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0006_alter_shipmenttrackmodel_shipment_track_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_order_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
