# Generated by Django 4.2.4 on 2023-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0007_alter_shipmenttrackmodel_shipment_track_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_order_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
