# Generated by Django 4.2.4 on 2023-09-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDetails_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderDetails_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'ordering': ('-OrderDetails_order',),
            },
        ),
        migrations.CreateModel(
            name='OrderMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_order_date', models.DateTimeField(auto_now_add=True)),
                ('order_is_finished', models.BooleanField(default=False)),
                ('order_details', models.ManyToManyField(through='order_orderdetail.OrderDetailsMODEL', to='product.productmodel')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-order_order_date',),
            },
        ),
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='OrderDetails_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_orderdetail.ordermodel'),
        ),
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='OrderDetails_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
    ]
