# Generated by Django 4.2.4 on 2023-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_orderdetail', '0002_alter_orderdetailsmodel_orderdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsmodel',
            name='OrderDetails_price',
            field=models.IntegerField(),
        ),
    ]
